export default [
  {
    id: 1,
    image: "/img/jaguar.png",
    name: "Jaguar XE L P250",
    rating: 4.8,
    reviews: 2.436,
    passagers: 4,
    transmission: "auto",
    condition: "Air Conditioning",
    doors: 4,
    price: 1800,
  },
  {
    id: 2,
    image: "/img/audi-r8.png",
    name: "Audi R8",
    rating: 4.6,
    reviews: 1.936,
    passagers: 2,
    transmission: "auto",
    condition: "Air Conditioning",
    doors: 2,
    price: 2100,
  },
  {
    id: 3,
    image: "/img/bmw.png",
    name: "BMW M3",
    rating: 4.5,
    reviews: 2.036,
    passagers: 4,
    transmission: "auto",
    condition: "Air Conditioning",
    doors: 4,
    price: 1800,
  },
  {
    id: 4,
    image: "/img/lamborghini.png",
    name: "Lamborghini Huracan",
    rating: 4.3,
    reviews: 2.236,
    passagers: 2,
    transmission: "auto",
    condition: "Air Conditioning",
    doors: 2,
    price: 2300,
  },
];
